In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [18]:
df=pd.read_csv('breast_cancer.csv')

In [19]:
df.head()

Clump thickness  Cell Size  Cell Shape  Marginal Adhesion  \
0                1          1           3                  1   
1                3          1           1                  2   
2                2          1           1                  2   
3                1          1           1                  1   
4                3          1           1                  1   

   Signle Cell size  Bare Nuclei  Bland  Nucleoli  Mitoses   class  
0                 2            1      1         1        1  Benign  
1                 2            1      1         1        1  Benign  
2                 2            1      1         1        1  Benign  
3                10            1      1         1        1  Benign  
4                 2            1      1         1        1  Benign

In [21]:
df.shape


(682, 10)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clump thickness    682 non-null    int64 
 1   Cell Size          682 non-null    int64 
 2   Cell Shape         682 non-null    int64 
 3   Marginal Adhesion  682 non-null    int64 
 4   Signle Cell size   682 non-null    int64 
 5   Bare Nuclei        682 non-null    int64 
 6   Bland              682 non-null    int64 
 7   Nucleoli           682 non-null    int64 
 8   Mitoses            682 non-null    int64 
 9   class              682 non-null    object
dtypes: int64(9), object(1)
memory usage: 53.4+ KB


In [25]:
df.describe().transpose()

count      mean       std  min  25%  50%  75%   max
Clump thickness    682.0  4.441349  2.822751  1.0  2.0  4.0  6.0  10.0
Cell Size          682.0  3.149560  3.067222  1.0  1.0  1.0  5.0  10.0
Cell Shape         682.0  3.212610  2.989991  1.0  1.0  1.0  5.0  10.0
Marginal Adhesion  682.0  2.832845  2.865805  1.0  1.0  1.0  4.0  10.0
Signle Cell size   682.0  3.227273  2.217198  1.0  2.0  2.0  4.0  10.0
Bare Nuclei        682.0  3.548387  3.645226  1.0  1.0  1.0  6.0  10.0
Bland              682.0  3.445748  2.451435  1.0  2.0  3.0  5.0  10.0
Nucleoli           682.0  2.865103  3.052547  1.0  1.0  1.0  4.0  10.0
Mitoses            682.0  1.604106  1.733792  1.0  1.0  1.0  1.0  10.0

In [38]:
for i in df.columns:
    print(df[i].unique())

[ 1  3  2  8  5  4  6  7  9 10]
[ 1  2  3  4  9  7  8  6  5 10]
[ 3  1  2  6  4  7  5  8 10  9]
[ 1  2  3  4  6 10  5  9  8  7]
[ 2 10  1  5  3  4  7  6  8  9]
[ 1  2  3  4  5 10  8  7  9  6]
[ 1  2  3  5  6  7  4  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  5  7  8  4  6 10]
['Benign' 'Malignant']


In [29]:
df.columns

Index(['Clump thickness', 'Cell Size', 'Cell Shape', 'Marginal Adhesion',
       'Signle Cell size', 'Bare Nuclei', 'Bland', 'Nucleoli', 'Mitoses',
       'class'],
      dtype='object')

In [39]:
df.isnull().sum()

Clump thickness      0
Cell Size            0
Cell Shape           0
Marginal Adhesion    0
Signle Cell size     0
Bare Nuclei          0
Bland                0
Nucleoli             0
Mitoses              0
class                0
dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [42]:
x=df.drop(['class'],axis=1)
y=df['class']

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [44]:
from sklearn.svm import SVC

In [45]:
svc=SVC(C=.1, kernel='linear', gamma=1)
svc.fit(x_train,y_train)

SVC(C=0.1, gamma=1, kernel='linear')

In [46]:
y_pred = svc.predict(x_test)
print(svc.score(x_train, y_train),svc.score(x_test,y_test))

0.9743119266055046 0.9708029197080292


In [47]:
confusion_matrix(y_pred, y_test)

array([[93,  1],
       [ 3, 40]], dtype=int64)

In [52]:
svc=SVC(kernel='rbf')
svc.fit(x_train, y_train)
print(svc.score(x_train,y_train), svc.score(x_test, y_test))

0.9761467889908257 0.9708029197080292


In [53]:
confusion_matrix(y_pred, y_test)

array([[93,  1],
       [ 3, 40]], dtype=int64)

In [50]:
svc=SVC(kernel='poly')
svc.fit(x_train, y_train)
print(svc.score(x_train,y_train), svc.score(x_test, y_test))

0.9743119266055046 0.9708029197080292


In [51]:
svc=SVC(kernel='sigmoid')
svc.fit(x_train, y_train)
print(svc.score(x_train,y_train), svc.score(x_test, y_test))

0.3963302752293578 0.34306569343065696
